# Generated by Django 3.0.2 on 2020-01-19 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='LookingFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_for', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['looking_for'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_interest', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['personal_interest'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_interest', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['prof_interest'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('stack', models.TextField(blank=True, max_length=300)),
                ('detail', models.TextField(blank=True, max_length=500)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('github', models.CharField(blank=True, max_length=255)),
                ('unread_message_counter', models.PositiveSmallIntegerField(default=0)),
                ('blocked', models.ManyToManyField(related_name='blocking_profile', through='profiles.Blocked', to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(blank=True, to='profiles.Language')),
                ('looking_for', models.ManyToManyField(blank=True, to='profiles.LookingFor')),
                ('personal_interests', models.ManyToManyField(blank=True, to='profiles.PersonalInterest')),
                ('prof_interests', models.ManyToManyField(blank=True, to='profiles.ProfessionalInterest')),
            ],
        ),
        migrations.CreateModel(
            name='Starred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('starred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_profiles', to=settings.AUTH_USER_MODEL)),
                ('starring_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_starrer', to='profiles.Profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='starred',
            field=models.ManyToManyField(related_name='starring_profile', through='profiles.Starred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blocked',
            name='blocking_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_blocker', to='profiles.Profile'),
        ),
    ]
