# Generated by Django 3.0.2 on 2020-01-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-pk']},
        ),
    ]
