# Generated by Django 3.2.13 on 2022-06-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220530_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stack',
        ),
        migrations.AddField(
            model_name='profile',
            name='ask_me',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='teach_me',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='detail',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
