# Generated by Django 3.2.17 on 2023-02-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mastodon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
