# Generated by Django 3.0.2 on 2020-01-19 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('approachee_unread_count', models.PositiveSmallIntegerField(default=0)),
                ('initiator_unread_count', models.PositiveSmallIntegerField(default=0)),
                ('latest_message_time', models.DateTimeField(null=True)),
                ('approachee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations_as_approachee', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations_as_initiator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-latest_message'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=2000)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='conversations.Conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': ['created'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='latest_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='conversations.Message'),
        ),
    ]
