# Generated by Django 3.2.13 on 2022-06-21 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_alter_conference_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='polling_interval',
        ),
    ]
