# Generated by Django 3.0.2 on 2020-04-22 05:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200131_2247'),
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetup',
            options={'ordering': ['start_date', 'start_time']},
        ),
        migrations.RenameField(
            model_name='meetup',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='meetup',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='meetup',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 5, 57, 54, 406476, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 4, 22, 5, 58, 4, 98915, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StarredMeetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meetups_starring_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_meetups_starrer', to='profiles.Profile')),
                ('starred_meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_meetup', to='meetups.Meetup')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='meetup',
            name='starred',
            field=models.ManyToManyField(related_name='starring_profile', through='meetups.StarredMeetup', to='profiles.Profile'),
        ),
    ]
